# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mone27.net',
                'doc_host': 'https://mone27.github.io',
                'git_url': 'https://github.com/mone27/mone27.net',
                'lib_path': 'mone27'},
  'syms': { 'mone27.core': {'mone27.core.Markdown': ('core.html#markdown', 'mone27/core.py')},
            'mone27.home': { 'mone27.home.blog_box': ('homepage.html#blog_box', 'mone27/home.py'),
                             'mone27.home.get_blogs': ('homepage.html#get_blogs', 'mone27/home.py')}}}
