# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/core.ipynb.

# %% auto 0
__all__ = ['Markdown']

# %% ../nbs/core.ipynb 1
from fasthtml.common import *

# %% ../nbs/core.ipynb 2
def Markdown(text):
    return Div(text, cls="marked")
