# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/homepage.ipynb.

# %% auto 0
__all__ = ['blog_box', 'get_blogs']

# %% ../nbs/homepage.ipynb 2
from fasthtml.common import *
from fasthtml.jupyter import *
from pyprojroot import here
from fastcore.all import L
from .core import *

# %% ../nbs/homepage.ipynb 3
def blog_box(title, content, max_len=120):
    excerpt = content[:max_len] + '...' if len(content) > max_len else content
    return Div(
        Markdown(excerpt),
        Button("Read more", onclick=f"location.href='/blog/{title}'"),
        style = "border: 2px solid white; padding: 10px; border-radius: 10px;"
    ) 


# %% ../nbs/homepage.ipynb 6
def get_blogs():
    posts = here('posts').ls()
    titles = posts.map(Self.stem())
    contents = posts.map(Self.read_text())
    return titles.zipwith(contents)
