[project]
authors = ["Simone Massaro <simone.massaro@mone27.net>"]
channels = ["conda-forge"]
description = "The Blog, Finally!"
name = "mone27.net"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
serve = "uvicorn index:app --port 8000 --host 0.0.0.0 --proxy-headers" 

[dependencies]
python = ">=3.12.6,<4"
fastcore = ">=1.7.9,<2"
nbdev = ">=2.3.31,<3"
pyprojroot = ">=0.3.0,<0.4"

[host-dependencies]
jupyterlab = ">=4.2.5,<5"

[pypi-dependencies]
python-fasthtml = { git = "https://github.com/answerdotai/fasthtml" }
mone27 = { path = ".", editable = true }
